In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("dataset.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
from io import StringIO
import pandas as pd  # Added import for pandas

csv_data=\
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.9,,8.0
10.0,11.0,12.0'''  # Removed trailing commas from lines 3 and 4

df=pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.9   NaN  8.0
2  10.0  11.0  12.0  NaN

In [5]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
df.values

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6.9,  nan,  8. ],
       [10. , 11. , 12. ,  nan]])

In [7]:
data.values

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [8]:
#dropping the rows containing missing or Nan values in data dataset using dropna


In [9]:
df.dropna(axis=0)


A    B    C    D
0  1.0  2.0  3.0  4.0

In [10]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.9
2  10.0  11.0

In [11]:
# !git add Data_preprocessing.ipynb
# !git commit -m "Data Preprocessing"
# !git push

In [12]:
##we use simpleImputer to replace the missing cell with the mean value of that whole column

In [13]:
from sklearn.impute import SimpleImputer
import numpy as np
imr=SimpleImputer(missing_values=np.nan,strategy='mean')
imr=imr.fit(df.values)
imputed_data=imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6.9,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [14]:
#using pandas to perform work performed by simpleimputer
df.fillna(df.mean())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.9   7.5  8.0
2  10.0  11.0  12.0  6.0

In [15]:
#to learn categorical encoding with pandas

In [16]:
import pandas as pd
df2=pd.DataFrame([
    ['green', 'M', 10.1, 'class2'],
    ['red', 'L', 13.5, 'class1'],
    ['blue', 'XL', 15.3, 'class2']])
df2.columns=['color','size','price','classlabel']
df2
    

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [17]:
size_mapping={'XL':3,
              'L':2,
              'M':1}
df2['size']=df2['size'].map(size_mapping)
df2

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [18]:
import numpy as np
class_mapping={label:idx for idx, label in
               enumerate(np.unique(df2['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [19]:
df2['classlabel']=df2['classlabel'].map(class_mapping)
df2

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [20]:
# !git add Data_preprocessing.ipynb
# !git commit -m "Data Preprocessing"
# !git push

In [22]:
#using labelencoder in sicikt learn
from sklearn.preprocessing import LabelEncoder
class_le=LabelEncoder()
y=class_le.fit_transform(df2['classlabel'].values)
y

array([1, 0, 1], dtype=int64)

In [23]:
x=df2[['color','size','price']].values
color_le=LabelEncoder()
x[:,0]=color_le.fit_transform(x[:,0])
x

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [24]:
#using one hot encoder

In [25]:
from sklearn.preprocessing import OneHotEncoder
x=df2[['color','size','price']].values
color_ohe=OneHotEncoder()
color_ohe.fit_transform(x[:,0].reshape(-1,1)).toarray()


array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder  # Added missing import

x = df2[['color', 'size', 'price']].values
c_trans = ColumnTransformer([  # Fixed typo: ColumnTransform -> ColumnTransformer
    ('onehot', OneHotEncoder(), [0]),
    ('nothing', 'passthrough', [1, 2])
])
c_trans.fit_transform(x).astype(float)  # Fixed variable name and removed indentation

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])

In [ ]:
!git add Data_preprocessing.ipynb
!git commit -m