In [10]:
#import matplotlib.pyplot as plt

In [11]:
# x=[i for i in range (10)]
# x

In [12]:
# y=[2*i for  i in range(10)]
# y

In [13]:

# plt.xlabel("x axis")
# plt.ylabel("y axis")
# plt.plot(x,y)


In [14]:
#plt.scatter(x,y)

In [15]:
#to save a model
#from sklearn.externals import joblib
#then after training a model let say name is "mode.sav"
#joblib.dump(clf,filename)





In [16]:
# from sklearn import datasets
# import numpy as np

# iris=datasets.load_iris()
# iris

In [17]:
# x=iris.data
# y=iris.target
# print(x,y)

In [18]:
# print(x.shape)
# print(y.shape)

In [19]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
# print(x_train.shape)

In [20]:
#print(x_test.shape)

In [21]:
##KNN algorithm

In [22]:
# from sklearn import neighbors, metrics
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder

In [23]:
# import pandas as pd
# car=pd.read_csv("car.data")
# car

In [24]:
# import pandas as pd

# # Load your dataset
# data = pd.read_csv("car.data")

# # Rename specific columns
# data= car.rename(columns={
#     'vhigh': 'buying',
#     'vhigh.1': 'maint',
#     '2': 'doors',
#     '2.1': 'persons',
#     'small': 'lug_boot',
#     'low': 'safety',
#     'unacc': 'class'
# })


In [25]:
# car

In [26]:
# x=car[[
#     'buying',
#     'maint',
#     'safety'
# ]].values
# y=data[['class']]
# print(x,y)

In [27]:
# #converting the data
# Le=LabelEncoder()
# for i in range(len(x[0])):
#     x[:,i]=Le.fit_transform(x[:,i])
# print(x)

In [28]:
# import pandas as pd

# # Assuming y is a DataFrame but might not be properly defined
# # First, make sure y is a DataFrame
# if not isinstance(y, pd.DataFrame):
#     # If y is a Series, convert to DataFrame
#     if isinstance(y, pd.Series):
#         y = y.to_frame(name='class')
#     # If y is a numpy array or list
#     else:
#         y = pd.DataFrame(y, columns=['class'])

# # Now define the mapping and apply it
# label_mapping = {
#     'unacc': 0,
#     'acc': 1,
#     'good': 2,
#     'vgood': 3
# }

# # Apply mapping to the 'class' column
# y['class'] = y['class'].map(label_mapping)
# y

In [29]:
##svm explained

In [30]:
# from sklearn import datasets
# import numpy as np
# from sklearn.model_selection import train_test_split
# iris=datasets.load_iris()
# iris

In [31]:
# from sklearn import svm
# x=iris.data
# y=iris.target
# classes=['Iris Setosa','Iris Versicolour','Iris Virginica']

# print(x.shape)
# print(y.shape)

In [32]:
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [33]:
# model=svm.SVC()
# model.fit(x_train,y_train)
# print(model)

In [34]:
# from sklearn.metrics import accuracy_score
# predictions=model.predict(x_test)
# accuracy=accuracy_score(y_test,predictions)
# print(predictions)
# print(accuracy)

In [35]:
#for i in range(len(predictions)):
  #  print(classes[predictions[i]])

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import scale
import pandas as pd


In [2]:
bc=load_breast_cancer()
bc

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
x=bc.data
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
x=scale(bc.data)
x

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [5]:
y=bc.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=6)

In [7]:
model=KMeans(n_clusters=2,random_state=0)

In [8]:
model.fit(x_train)

D:\conda\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


KMeans(n_clusters=2, random_state=0)

In [9]:
predictions=model.predict(x_test)

In [10]:
labels=model.labels_

In [11]:
print('labels',labels)
print('predictions',predictions)
print('accuracy:',accuracy_score(y_test,predictions))
print('actual',y_test)

labels [0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1
 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1
 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0
 1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0
 1 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0
 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0
 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0
 0 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 1 0 1 1 0 0 1 0 1

In [12]:
print(pd.crosstab(y_train,labels))

col_0    0    1
row_0          
0       36  175
1      334   18
