In [ ]:
# import tarfile
# with tarfile.open('aclImdb_v1.tar.gz','r:gz') as tar:
#     tar.extractall()

In [ ]:
#!pip install pyprind

In [ ]:
#import pyprind
# import pandas as pd
# import os
# import sys

# basepath = r'C:\Users\yogendra singh\ML-with-pytorch-and-scikit-learn\aclImdb'
# labels = {'pos': 1, 'neg': 0}
# pbar = pyprind.ProgBar(50000, stream=sys.stdout)

# # Create an empty list to store the data
# data = []

# for s in ('test', 'train'):
#     for l in ('pos', 'neg'):
#         path = os.path.join(basepath, s, l)
#         for file in sorted(os.listdir(path)):
#             with open(os.path.join(path, file),
#                       'r', encoding='utf-8') as infile:
#                 txt = infile.read()
#                 # Append to list instead of using DataFrame.append()
#                 data.append([txt, labels[l]])
#                 pbar.update()

# # Create DataFrame from the collected data
# df = pd.DataFrame(data, columns=['review', 'sentiment'])

In [ ]:
# import numpy as np
# import pandas as pd
# np.random.seed(0)
# df=df.reindex(np.random.permutation(df.index))
# df.to_csv('movie_data.csv',index=False,encoding='utf-8')


In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('movie_data.csv',encoding='utf-8')
df=df.rename(columns={"0":"review","1":"sentiment"})
df.head(3)

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0

In [4]:
df.shape

(50000, 2)

In [11]:
#Transforming words into features vectors
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()
docs=np.array(['The sun is shining',
               'The weather is sweet',
               'The sun is shining, the weather is sweet,'
               'and one and one is two'])
bag=count.fit_transform(docs)


In [12]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [13]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [14]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer(use_idf=True,
                       norm='l2',
                       smooth_idf=True)
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs))
      .toarray())

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]
